### ISSUE TITLE
As a developer I want to have a secure platform

### ISSUE THREAD

**Issue by JonasGredig** [LaurentMouchart/Infodisplay#17]
- [X] Storyline
- [X] Assign tags
- [X] Acceptance criteria

* CSRF
* XSS
* SQL Injection
* All others

**Comment by AndrinKappeler** [comment]
The tools we use are very secure. We have to make sure that the our versions of Angular and Spring are updated.

**Comment by AndrinKappeler** [comment]
The tools we use are very secure. We have to make sure that the our versions of Angular and Spring are updated.

**Comment by BenjaminRaison** [comment]
Have you tested it?
